INSTAGRAM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings # 관례
from accounts import views as accounts_views # 관례
from posts import views  as posts_views 

urlpatterns = [
    path('',posts_views.list, name="root"),
    path('admin/', admin.site.urls),
    path('posts/',include('posts.urls')),
    path('accounts/',include('accounts.urls')),
    path('<str:username>/', accounts_views.profile, name="profile"), # 이번엔 다른 보조에게 넘기지 말고 바로
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 관례임

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/',views.signup, name="signup"),
    path('logout/',views.logout, name="logout"),
    path('login/',views.login, name="login"),
    path('delete/',views.delete,name="delete"),
    path('<int:user_id>/follow/',views.follow, name="follow"),
    path('change_profile/',views.change_profile,name="change_profile"),
    ]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('create/',views.create, name="create"),
    path('',views.list,name="list"),
    path('<int:post_id>/delete/',views.delete, name="delete"),
    path('<int:post_id>/update/', views.update, name="update"),
    path('<int:post_id>/comments/create/', views.create_comments, name="create_comments"),
    path('<int:post_id>/like/',views.like, name="like"),
    ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")
    # 여기가 포인트 다른 놈이 나를 부를 때 follwers가 아니라 following이니까 realted_name 요로케 줘야함
    
class Profile(models.Model):
    description = models.TextField(blank=True)
    nickname = models.CharField(max_length=40, blank=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE) # 1:1 일 때는 이 Field를 사용 / 모델에서는 settings.AUTH_USER_MODEL 쓰기로 했다.
    image = models.ImageField()
    
    
    def __str__(self):
        return f"{self.user.username}의 프로필"

posts/models.py
from django.db import models
from django.conf import settings 

# Create your models here.
class Post(models.Model):
    content = models.CharField(max_length=140)
    image = models.ImageField(blank=True)
    # User와의 연결고리를 만들어줘야 함. YGGR 1 (1:N)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 실제 DB에는 user객체가 들어가는 게 아니라 user_id 만 만들어져서 들어감
    # ForeignKey(Modelclass, Options)
    # User를 import 해서 안쓰는 이유는 장고가 이미 포장해서 다른 말로 만들어놨으니까 그거 쓰려구
    
    # User와의 YGGR 2 (M:N) Like
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_post",blank=True)
    
    def __str__(self):
        return f"{self.id} : {self.content[:20]}"
        
    def __repr__(self):
        return f"{self.id} : {self.content[:20]}"
        
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from .models import Profile

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields
    
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['description','nickname','image']
        
        

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth import login as auth_login # 이러케 하는 이유는 밑에 정의할 login 함수랑 겹쳐서 라이브러리 설명은 공식문서 찾아주셈
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from .forms import ProfileForm

# Create your views here.
def signup(request):
    # 회원가입
    if request.method == "POST": 
        form = CustomUserCreationForm(request.POST)
        if form.is_valid(): # 야 폼아 혹시 넘어온 데이터 괜찮닝
            user = form.save() # 방금 가입한 유저
            # 가입된 유저의 Profile 레코드 함께 생성
            Profile.objects.create(user=user) # 이렇게 하면 다른 필드는 비었지만 user 만 채워진 프로필 모델이 생긴다.
            auth_login(request,user)
        return redirect('posts:list')
    else:
        form = CustomUserCreationForm()
        context = {
            'form':form,
        }
        return render(request, 'accounts/signup.html',context)
        
def logout(request):
    auth_logout(request)
    return redirect('posts:list')

def login(request):
    if request.method == "POST":
        # 실제 로그인 (세션에 유저 정보를 넣는다.)
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user()) # form.get_user 는 form 으로 부터 유저 정보를 가져오는 함수
        return redirect('posts:list')
            
    else:
        # 유저로부터 username과 비밀번호를 받는다.
        form = AuthenticationForm()
        context = {
            'form':form
        }
        return render(request, 'accounts/login.html',context)

@login_required       
def profile(request, username):
    # username을 가진 유저의 상세 정보를 보여주는 페이지
    profile = get_object_or_404(get_user_model(), username=username)
    context = {
        'profile':profile
    }
    return render(request,'accounts/profile.html',context)

@login_required    
def delete(request):
    # POST -> 계정을 삭제한다. == DB에서 user를 삭제한다.
    if request.method == "POST":
        request.user.delete()
        return redirect('accounts:signup')
    # GET -> 진짜 삭제하시겠습니까?
    return render(request,'accounts/delete.html')

@login_required
def follow(request, user_id): # 내가 팔로우 할 사람이 넘어 온다.
    person = get_object_or_404(get_user_model(), pk=user_id) # 내가 팔로우 하려는 사람을 일단 찾아.
    # 만약 이미 팔로우한 사람이라면,
    if request.user in person.followers.all(): # 내가(로그인한 사용자) 펄슨의 팔로우 들에 이미 있다면
        # 언팔
        person.followers.remove(request.user)
    # 아직 안했다면
    else:
        # 팔
        person.followers.add(request.user)
    return redirect('profile',person.username)
    
@login_required
def change_profile(request):
    # 프로필 정보 수정
    if request.method == "POST":
        profile_form = ProfileForm(data=request.POST,instance=request.user.profile,files=request.FILES) # 뒤에것이 수정 대상 앞에것이 수정에 들어갈 데이터
        if profile_form.is_valid():
            profile_form.save()
            return redirect('profile',request.user.username)
    else:
        profile_form = ProfileForm(instance=request.user.profile) # 장고 똑똑해서 1:1은 profile_set 이 아니라 걍 단수로. 굿.
        context = {
            'profile_form' : profile_form
        }
        return render(request, 'accounts/change_profile.html',context)

accounts/templates/accounts/change_profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<h1>프로필수정</h1>
<form method="POST" enctype="multipart/form-data"> 
  {% csrf_token %}
  {% bootstrap_form profile_form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">프로필변경</button>
  {% endbuttons %}
</form>
{% endblock %}

accounts/templates/accounts/delete.html
{% extends 'base.html' %}
{% block body %}
    <h1> 정말로 탈퇴하실 건가요</h1>
    <form action="{% url 'accounts:delete' %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-dark" type="submit">가지마세요</button>
    </form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<h1>로그인</h1>
<form method="POST"> 
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">로그인</button>
  {% endbuttons %}
</form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block body %}
 <div class="row">
   <div class="col-3">
     {% if profile.profile.image %}
       <img src="{{ profile.profile.image.url }}" class="rounded-circle">
     {% else %}
       <i class="fas fa-user-circle fa-10x"></i>
     {% endif %}
     <h1>{{ profile.username }}
       {% if user != profile %}
         {% if user in profile.followers.all %}
           <a class="btn btn-dark" href="{% url 'accounts:follow' profile.id %}">언팔로우</a>
         {% else %}
           <a class="btn btn-primary" href="{% url 'accounts:follow' profile.id %}">팔로우</a>
         {% endif %}
       {% endif %}
     </h1>
   </div>
   <div class="col-9">
     <div>
       <strong>{{ profile.profile.nickname }}</strong>
     </div>
     <div>
       {{ profile.profile.description }}
     </div>
   </div>
 </div>

 {% if user == profile %}
   <a class="btn btn-danger" href="{% url 'accounts:delete' %}">회원탈퇴</a>
   <a class="btn btn-info" href="{% url 'accounts:change_profile' %}">프로필 변경</a>
 {% endif %}


 <div class="row">
   <!-- 해당 유저가 작성한 모든 post를 보여줌 -->
   {% for post in profile.post_set.all %}
     <div class="col-4">
       <img src="{{ post.image.url }}" class="image-fluid" alt="...">
     </div>
   {% endfor %}

 </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<h1>회원가입</h1>
<form method="POST"> 
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">회원가입</button>
  {% endbuttons %}
</form>
{% endblock %}