INSTAGRAM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings # 관례
from accounts import views as accounts_views # 관례
from posts import views  as posts_views 

urlpatterns = [
    path('',posts_views.list, name="root"),
    path('admin/', admin.site.urls),
    path('posts/',include('posts.urls')),
    path('accounts/',include('accounts.urls')),
    path('<str:username>/', accounts_views.profile, name="profile"), # 이번엔 다른 보조에게 넘기지 말고 바로
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 관례임

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/',views.signup, name="signup"),
    path('logout/',views.logout, name="logout"),
    path('login/',views.login, name="login"),
    path('delete/',views.delete,name="delete"),
    path('<int:user_id>/follow/',views.follow, name="follow"),
    path('change_profile/',views.change_profile,name="change_profile"),
    ]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('create/',views.create, name="create"),
    path('',views.list,name="list"),
    path('<int:post_id>/delete/',views.delete, name="delete"),
    path('<int:post_id>/update/', views.update, name="update"),
    path('<int:post_id>/comments/create/', views.create_comments, name="create_comments"),
    path('<int:post_id>/like/',views.like, name="like"),
    ]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <title>INSTAGRAM</title>
  </head>
  <body>
    {% include 'nav.html' %}
    <div class="container">
      {% block body %}
      {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'posts:list' %}"> 
    <i class="fab fa-instagram fa-lg"></i> Instagram
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'profile' user.username %}" tabindex="-1" aria-disabled="true">{{ user }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'posts:create' %}">새글 쓰기</a></a> 
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a></a> 
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a> 
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a> <!--수정-->
      </li>
      {% endif %}
    </ul>
  </div>
</nav>