INSTAGRAM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings # 관례
from accounts import views as accounts_views # 관례
from posts import views  as posts_views 

urlpatterns = [
    path('',posts_views.list, name="root"),
    path('admin/', admin.site.urls),
    path('posts/',include('posts.urls')),
    path('accounts/',include('accounts.urls')),
    path('<str:username>/', accounts_views.profile, name="profile"), # 이번엔 다른 보조에게 넘기지 말고 바로
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 관례임

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('create/',views.create, name="create"),
    path('',views.list,name="list"),
    path('<int:post_id>/delete/',views.delete, name="delete"),
    path('<int:post_id>/update/', views.update, name="update"),
    path('<int:post_id>/comments/create/', views.create_comments, name="create_comments"),
    path('<int:post_id>/like/',views.like, name="like"),
    ]

posts/models.py
from django.db import models
from django.conf import settings 

# Create your models here.
class Post(models.Model):
    content = models.CharField(max_length=140)
    image = models.ImageField(blank=True)
    # User와의 연결고리를 만들어줘야 함. YGGR 1 (1:N)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 실제 DB에는 user객체가 들어가는 게 아니라 user_id 만 만들어져서 들어감
    # ForeignKey(Modelclass, Options)
    # User를 import 해서 안쓰는 이유는 장고가 이미 포장해서 다른 말로 만들어놨으니까 그거 쓰려구
    
    # User와의 YGGR 2 (M:N) Like
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_post",blank=True)
    
    def __str__(self):
        return f"{self.id} : {self.content[:20]}"
        
    def __repr__(self):
        return f"{self.id} : {self.content[:20]}"
        
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

posts/forms.py
from django import forms
from .models import Post, Comment

class PostModelForm(forms.ModelForm): # 모델 폼 양식
    content = forms.CharField(
        label="content",
        widget = forms.Textarea(attrs={ # 여기 들어가는 게 속성값들
                'rows' : 5,
                'cols' : 50,
                'placeholder' : '지금 뭘 하고 계신가?',
            }))
        
    class Meta: # 디자인 부분
        model = Post # 어떤 모델에 대해서 만들지 먼저 말해주고
        # fields = '__all__' # 요로케 하면 그 모델에 대한 모든 필드에 대한 input이 만들어지지만 모두 가져올 필요가 별로 없음
        fields = ['content','image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostModelForm, CommentForm
from .models import Post, Comment
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def create(request):
    
    # 만약, POST 요청이 오면
    if request.method == 'POST':
        # 글을 작성하기
        form = PostModelForm(request.POST, request.FILES) # 모델폼으로 넘어온 데이터를 정리
        
        if form.is_valid(): # 유효성 검사
            post = form.save(commit=False) # save는 하고 db에 저장은 하지 마라
            post.user = request.user # 객체를 때려박아도 장고가 알아서 id 만 따와서 들어간다.
            post.save()
            return redirect('posts:list') # 일단은 리다렉
        
    
    # 아니고, GET 요청이 오면
    else: 
        # post를 작성하는 폼을 가져와 template에서 보여준다.
        form = PostModelForm()
        context = {
            'form':form
        }
        return render(request,'posts/create.html',context)

@login_required
def list(request):
    # 접속한 유저가 팔로잉한 유저들의 Post만 보여준다.
    # 동영 ver.
    # posts = []
    # for following in request.user.followings.all():
    #     posts.extend(Post.objects.filter(user=follwing))
    # 요거는 속도가 좀 안날 수도 있다.
    # 항상 데이터 찾는거는 DB에 시키자.
    # 쌤 ver.
    posts = Post.objects.filter(user__in=request.user.followings.values('id')).order_by('-pk')
    
    comment_form = CommentForm()
    context = {
        'posts':posts,
        'comment_form':comment_form,
    }
    return render(request,'posts/list.html',context)

@login_required
def delete(request, post_id):
    post = Post.get_object_or_404.get(Post,pk=post_id)
    
    if post.user != request.user:
        return redircet('posts:list')
    
    post.delete()
    return redirect('posts:list')

@login_required
def update(request, post_id):
    
    post = Post.get_object_or_404.get(Post,pk=post_id)
    
    if post.user != request.user:
        return redircet('posts:list')
        
    # POST 요청일 때
    if request.method == "POST":
        # 수정내용 DB에 반영
        form = PostModelForm(request.POST, instance=post) # 여기가 create 이랑 다른점
        if form.is_valid():
            form.save()
            return redirect('posts:list') # 디테일 아직 없으니까 일단 list
    
    # GET 요청일 때
    else:
        # 수정 내용 편집
        form = PostModelForm(instance=post) # 요로케 넘겨야 value 뜸
        context = {
            'form' : form,
        }
        return render(request, 'posts/update.html', context)

@login_required
def create_comments(request, post_id):
    comment_form = CommentForm(request.POST)
    
    if comment_form.is_valid():
        comment = comment_form.save(commit=False) # 일단 
        comment.user = request.user # 누가 작성했는지 넣어주고
        comment.post_id = post_id
        comment.save()
        return redirect('posts:list')
        
@login_required
def like(request,post_id):
    # 특정 유저가 특정 포스트를 좋아요 할 때
    post = get_object_or_404(Post,id=post_id) # 특정 유저는 request.user로 들어올 것.. 
    # 특정 포스트는 위처럼
    
    # 만약 좋아요가 되어 있다면,
    # -> 좋아요를 해제한다.
    if request.user in post.like_users.all(): # 만약 좋아요가 되어 있다면,
         post.like_users.remove(request.user)
     
    # 아니면
    # -> 좋아요를 한다.
    else:
        post.like_users.add(request.user) 
    
    return redirect('posts:list')

posts/templates/posts/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<h1>새로운 Post 작성하기</h1>
<form method="POST" enctype="multipart/form-data"> <!--액션 줄 필요는 없다--> <!--사진 업로드 기능이 있을 때는 enctype 붙여줘야 한다.-->
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">업로드</button>
  {% endbuttons %}
</form>
{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
  <!-- 모든 post를 보여줌-->
  <div class="row justify-content-center">
    {% for post in posts %}
      <div class="card" style="width: 40rem;">
        <div class="card-header">
          <span><a href="{% url 'profile' post.user.username %}">{{ post.user.username }}</a></span>
        </div>
        <img src="{{ post.image.url }}" class="card-img-top" alt="...">
        <div class="card-body">
          <a href="{% url 'posts:like' post.id %}">
            <!-- 만약 현재 접속한 유저가 좋아요를 한적이 있으면-->
            {% if user in post.like_users.all %}
              <i class="fas fa-heart"></i>
            <!-- 아직 좋아요 안 했으면 -->
            {% else %}
              <i class="far fa-heart"></i>
            {% endif %}
          </a>
          <p class="card-text">
            {{ post.like_users.all.count }} 명이 좋아합니다.
          </p>
        </div>
        
        <div class="card-body">
          <p class="card-text">{{ post.content }}</p>
          <!-- 본인의 글만 삭제, 수정 버튼이 보이도록 -->
          {% if request.user == post.user %}
            <a class="btn btn-danger" href="{% url 'posts:delete' post.id %}">삭제</a>
            <a class="btn btn-success" href="{% url 'posts:update' post.id %}">수정</a>
          {% endif %}
          <form method="POST" action={% url 'posts:create_comments' post.id %}>
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            <button type="submit" class="btn btn-warning">댓글 달기</button>
          </form>
          <div>
            {% for comment in post.comment_set.all %}
              <p>
                {{ comment.content }}
              </p>
            {% endfor %}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<h1>수정 하기</h1>
<form method="POST"> <!--액션 줄 필요는 없다-->
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">업로드</button>
  {% endbuttons %}
</form>
{% endblock %}